# This is a basic workflow to help you get started with Actions

name: Build

on:
  workflow_call:
    inputs:
      param:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Do the build
        run: echo The reusable workflow param is ${{ inputs.param }}
