# This is a basic workflow to help you get started with Actions

name: Build

on:
  workflow_call:
    inputs:
      param:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Reusable workflow step input: ${{ inputs.param }}"
        
